[WeeklyReport] yuan20041218 2024.11.18~2023.11.29
PFCCLab/Starter pull request #437
Opened 2024-12-01 06:40 UTC by yuan20041218

2024-12-01 11:02 UTC, yuan20041218 commented
老师什么时候审查呀

2024-12-01 11:27 UTC, MrXnneHang commented
不急，你可以先改。PR提交了就行。不一定要在今天前合入。

2024-12-01 11:53 UTC, yuan20041218 commented
老师我需要修改哪里

2024-12-01 12:04 UTC, MrXnneHang requested changes

2024-12-01 12:21 UTC, yuan20041218 commented on Reports/season 4/yuan20041218/[WeeklyReport]2024.11.18~2024.11.29.md
> +   - CodeStyle[B-16] #69605
好的老师

2024-12-02 09:19 UTC, mattheliu commented
LGTM

2024-12-02 09:29 UTC, mattheliu approved these changes

2024-12-02 09:29 UTC, merged